apiVersion: v1
kind: Service
metadata:
  name: zio-flink-operator
  namespace: bigdata-lab
  labels:
    app.kubernetes.io/name: zio-flink-operator
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: zio-flink-operator
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30881
  type: NodePort
